"""Audit the scroll story the way audit_brief_numbers.py audits the brief: every numeral in the
page's prose must be written by update_numbers.py (recorded in .numbers_owned.json) or be a listed
design constant. Also fails if update_numbers --check finds index.html stale against results.csv.

Prose = text outside <script>/<style>. The data arrays inside <script> (BARDATA, RANKDATA, BOUNDS,
ARRIVALS) are covered by the --check: the updater regenerates them and any drift fails there.
Not covered, by design: dates and timeline positions (metadata from timeline_events.csv), map style
numbers, and the per-building data .js files (generated by the exporters).

Usage: python audit_numbers.py   (run from anywhere; exit 1 on any finding)
"""
import html, json, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).parent
r = subprocess.run([sys.executable, str(HERE / "update_numbers.py"), "--check"], capture_output=True, text=True)
if r.returncode:
    raise SystemExit(r.stdout + r.stderr)
owned = set(json.loads((HERE / ".numbers_owned.json").read_text()))

# design constants and metadata that are legitimately typed by hand, with the reason
ALLOW = {
    "2026": "year", "24": "24 June, the event date", "72": "the 72-hour window (a design constant of the argument)",
    "400": "400+ MapSwipe volunteers (campaign metadata)", "0": "axis tick", "50": "axis tick", "100": "axis tick",
    "1": "'any 1 of 6' / 'Day 1' labels", "2": "'2 or more' / 'Day 2'", "3": "labels", "4": "'4 or more' / 'Day 4'",
    "5": "'5 or more' / 'Day 5'", "6": "'all 6'", "7": "'Day 7'", "10": "10 m matching radius (design parameter)", "20": "20 m",
}

t = (HERE / "index.html").read_text()
prose = re.sub(r"<script.*?</script>|<style.*?</style>", " ", t, flags=re.S)
prose = html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", prose)))
bad = []
for m in re.finditer(r"(?<![\w.])(\d(?:[\d,]*\d)?(?:\.\d+)?)(?![\w])", prose):
    n = m.group(1)
    if n in owned or n in ALLOW:
        continue
    bad.append((n, prose[max(0, m.start() - 50):m.end() + 40]))
if bad:
    print(f"audit_numbers: {len(bad)} numeral(s) in the story prose are neither written by update_numbers nor allowlisted:")
    for n, ctx in bad:
        print(f"  {n:>8}  …{ctx}…")
    sys.exit(1)
print(f"audit_numbers: story prose clean — {len(owned)} numerals written by update_numbers, the rest are listed design constants")
