"""One-time server-side copy: legacy un-evented tiers -> event=<id>/ (spec §4).

Copies bronze/silver/gold/platinum working tiers into their event-keyed layout:
  <tier>/<rest>  ->  <tier>/event=<EVENT>/<rest>
COPY, never move — the legacy tree stays untouched for every live reader.

Exclusions:
  * source=codab/ (shared reference tree, stays outside events — spec §3)
  * anything already under event= (re-run safety; never recurse)
  * gold-prod/ + platinum-prod/ (published copies are regenerated by promote.py)

Server-side (Copy Blob within the account) like promote.py: data never transits
this machine. Re-runnable: same-size existing copies are skipped. Ends with a
count+bytes verification table per tier and exits non-zero on mismatch.

Run: uv run --group etl python scripts/copy_event_tree.py [--dry-run]
"""

from __future__ import annotations

import sys
import time

from azure.core.exceptions import ResourceExistsError
from azure.storage.blob import BlobServiceClient
from azure.storage.filedatalake import DataLakeServiceClient

from gie import events
from gie.config import load_settings

EVENT = events.require_event("20260624-ve-earthquake")
TIERS = ["bronze", "silver", "gold", "platinum"]  # working copies only


def _files(fs, project_prefix: str, tier: str) -> dict[str, int]:
    """name -> size for real files under a tier ({} if tier absent)."""
    try:
        return {
            p.name: p.content_length
            for p in fs.get_paths(path=f"{project_prefix}/{tier}", recursive=True)
            if not p.is_directory
        }
    except Exception as e:  # tier truly absent is the only acceptable miss
        print(f"  {tier}/: listing failed ({e}); treating as absent")
        return {}


def main() -> None:
    dry = "--dry-run" in sys.argv
    s = load_settings("dev")
    blob_url = f"https://{s.account_host}"
    dfs_url = f"https://{s.account_name}.dfs.core.windows.net"
    read_sas = s.sas_token()  # source reads for the server-side copy
    src_fs = DataLakeServiceClient(dfs_url, credential=read_sas).get_file_system_client(s.container)
    dst_fs = DataLakeServiceClient(dfs_url, credential=s.sas_token(write=True)).get_file_system_client(s.container)
    dst_blob = BlobServiceClient(blob_url, credential=s.sas_token(write=True))

    failures = 0
    for tier in TIERS:
        base = f"{s.project_prefix}/{tier}/"
        all_files = _files(src_fs, s.project_prefix, tier)
        src = {
            n: sz
            for n, sz in all_files.items()
            if not n[len(base):].startswith("event=")          # never recurse
            and not n[len(base):].startswith("source=codab/")  # shared reference
        }
        done = {
            n: sz for n, sz in all_files.items()
            if n[len(base):].startswith(f"event={EVENT}/")
        }
        copied = skipped = 0
        made_dirs: set[str] = set()
        for name, size in sorted(src.items()):
            dst = f"{base}event={EVENT}/{name[len(base):]}"
            if done.get(dst) == size:
                skipped += 1
                continue
            if dry:
                copied += 1
                continue
            dpath = dst.rsplit("/", 1)[0]  # HNS: the copy target dir must exist
            if dpath not in made_dirs:
                try:
                    dst_fs.create_directory(dpath)
                except ResourceExistsError:
                    pass
                made_dirs.add(dpath)
            # Server-side Copy Blob + poll (verbatim pattern from promote.py):
            # data never transits this machine; poll get_blob_properties().copy.status
            # rather than trusting the start_copy_from_url() return value.
            bc = dst_blob.get_blob_client(s.container, dst)
            bc.start_copy_from_url(f"{blob_url}/{s.container}/{name}?{read_sas}")
            status = "pending"
            for _ in range(120):  # same-account copy is near-instant; guard anyway
                status = bc.get_blob_properties().copy.status
                if status != "pending":
                    break
                time.sleep(0.5)
            if status != "success":
                raise RuntimeError(f"copy failed ({status}): {dst}")
            copied += 1

        # verification: recount the copy and compare counts + total bytes
        post = {
            n: sz for n, sz in _files(dst_fs, s.project_prefix, tier).items()
            if n[len(base):].startswith(f"event={EVENT}/")
        }
        ok = dry or (len(post) == len(src) and sum(post.values()) == sum(src.values()))
        failures += 0 if ok else 1
        print(
            f"{tier}/: src {len(src)} files / {sum(src.values()):,} B -> "
            f"copy {len(post)} files / {sum(post.values()):,} B  "
            f"(copied {copied}, skipped {skipped}) {'[dry-run] ' if dry else ''}{'OK' if ok else 'MISMATCH'}"
        )
    if failures:
        sys.exit(f"{failures} tier(s) MISMATCHED — do not proceed to cutover.")
    print("done — record this table in data_ledger.md (freeze evidence, spec §5).")


if __name__ == "__main__":
    main()
